CREATE DATABASE app_development;
CREATE DATABASE app_test;
CREATE USER app WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE app_development TO app;
GRANT ALL PRIVILEGES ON DATABASE app_test TO app;
