FROM debian:10

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    libgtk2.0-dev \
    libtiff-dev \
    libgomp1 \
    pkg-config \
    manpages-dev \
    gcc-8 \
    g++-8 \
    cmake \
    gdb \
    vim \
    psmisc
